services:

  fr:
    build:
      context: ./../fr
      dockerfile: ./../fr/fr.dockerfile
    restart: always
    ports:
      - "8080:80"
    environment:
      REGISTERED_NUMBER: "25438296000158"
      TOKEN: "1d52a9b6b78cf07b08586152459a5c90"
      PLATFORM_CODE: "5AKVkHqCn"

  mongo:
    image: 'mongo:4.2.16-bionic'
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: fr
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db-data/mongo:/data/db